trigger:
  branches:
    include:
    - master
    - 15x

jobs:
  - job: Windows_x86
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            git submodule update --init
            git lfs install
            git lfs pull
            python build.py x86

      - task: BatchScript@1
        inputs:
          filename: 'release_tool.bat'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'Effekseer150Win'
          ArtifactName: 'Effekseer152gWin_x86'
          publishLocation: 'Container'

  - job: MacOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            git submodule update --init
            git lfs install
            git lfs pull
            PACKAGEING_FOR_MAC=1 MONO_SDK_PATH=/Library/Frameworks/Mono.framework/Versions/5_18_1 python3 build.py

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'Dev/Effekseer.dmg'
          ArtifactName: 'EffekseerMacDmg'
          publishLocation: 'Container'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'EffekseerMac'
          ArtifactName: 'Effekseer152gMac'
          publishLocation: 'Container'